name: .NET

on:
  push:
    branches: [ feature/dotnet-solution ]
  pull_request:
    branches: [ feature/dotnet-solution ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./CM.WeeklyTeamReport
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./CM.WeeklyTeamReport
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: ./CM.WeeklyTeamReport
    - name: Codecov upload
      uses: codecov/codecov-action@v2
